stages:
  - validate
  - compile
  - test
  - security
  - package
  - quality
  - deploy

validate:
  stage: validate
  image: node:latest
  before_script:
    - npm install -g htmlhint
  script:
    - htmlhint src/index.html || true

compile:
  stage: compile
  script:
    - echo "Pas de compilation nécessaire pour du HTML/CSS/JS"

test:
  stage: test
  image: node:latest
  before_script:
    - npm install -g stylelint stylelint-config-standard
  script:
    - stylelint "src/css/*.css"

security:
  stage: security
  image: openjdk:21-slim
  before_script:
    - apt-get update && apt-get install -y wget unzip
    - wget -O ZAP_2_14_0.zip https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2_14_0.zip
    - unzip ZAP_2_14_0.zip -d zap
    - export PATH=$PATH:$(pwd)/zap/ZAP_2.14.0
    - chmod +x zap/ZAP_2.14.0/zap.sh
  script:
    - zap/ZAP_2.14.0/zap.sh -cmd -quickurl http://localhost:8080 -quickprogress


package:
  stage: package
  script:
    - tar -cvf mywebapp.tar.gz src/
  artifacts:
    paths:
      - mywebapp.tar.gz

quality:
  stage: quality
  script:
    - echo "Contrôle qualité terminé"
deploy:
  stage: deploy
  script:
    - mkdir public
    - cp -r src/* public/
  artifacts:
    paths:
      - public
  only:
    - main
